const products = [
    {
      id: 1,
      name: "Apple",
      image: require('../assets/imgs/apple.png'),
      price: 1.00,
      description: "Fresh red apple.",
      type:'fruits',
    },
    {
      id: 2,
      name: 'Banana',
      image: require('../assets/imgs/banana.png'),
      price: 0.50,
      description: "Ripe yellow banana.",
      type:'fruits',
    },
    {
      id: 3,
      name: "Orange",
      image: require('../assets/imgs/orange.png'),
      price: 0.80,
      description: "Sweet and tangy orange.",
      type:'fruits',
    },
    {
      id: 4,
      name: "Grapes",
      image: require('../assets/imgs/grapes.png'),
      price: 2.00,
      description: "A bunch of fresh grapes.",
      type:'fruits',
    },
    {
      id: 5,
      name: "Strawberries",
      image: require('../assets/imgs/strawberries.png'),
      price: 3.00,
      description: "Delicious and sweet strawberries.",
      type:'fruits',
    },
    {
      id: 6,
      name: "Watermelon",
      image: require('../assets/imgs/watermelon.png'),
      price: 5.00,
      description: "Large, refreshing watermelon.",
      type:'fruits',
    },
    {
      id: 7,
      name: "Pineapple",
      image: require('../assets/imgs/pineapple.png'),
      price: 4.00,
      description: "Tropical pineapple.",
      type:'fruits',
    },
    {
      id: 8,
      name: "Mango",
      image: require('../assets/imgs/mango.png'),
      price: 2.50,
      description: "Juicy and ripe mango.",
      type:'fruits',
    },
    {
      id: 9,
      name: "Blueberries",
      image: require('../assets/imgs/blueberries.png'),
      price: 3.50,
      description: "Fresh and healthy blueberries.",
      type:'fruits',
    },
    {
      id: 10,
      name: "Peach",
      image: require('../assets/imgs/peach.png'),
      price: 1.20,
      description: "Sweet and juicy peach.",
      type:'fruits',
    },
    {
      id: 11,
      name: "Egg",
      image: require('../assets/imgs/egg.png'),
      price: 0.20,
      description: "Fresh farm eggs.",
      type:'egg',
    },
    {
      id: 12,
      name: "Chips",
      image: require('../assets/imgs/chips.png'),
      price: 1.50,
      description: "Crispy chips.",
      type:'chips',
    },
    {
      id: 13,
      name: "Noodles",
      image: require('../assets/imgs/noodles.png'),
      price: 2.00,
      description: "Instant noodles with rich flavor.",
      type:'noddles',
    },
    {
      id: 14,
      name: "Fast Food",
      image: require('../assets/imgs/fastfood.png'),
      price: 5.00,
      description: "Delicious fast food meal.",
      type:'fast food',
    },
    {
      id: 15,
      name: "Bread",
      image: require('../assets/imgs/bread.png'),
      price: 1.00,
      description: "Freshly baked bread loaf.",
      type:'Bread',
    },
    {
      id: 16,
      name: "Cheese",
      image: require('../assets/imgs/cheese.png'),
      price: 2.00,
      type:'cheese',
      description: "delicious cheese.",
    },
    {
      id: 17,
      name: "Milk",
      image: require('../assets/imgs/milk.png'),
      price: 1.50,
      type:'Milk',
      description: "Pure and fresh milk.",
    },
    {
      id: 18,
      name: "Butter",
      image: require('../assets/imgs/butter.png'),
      price: 1.20,
      description: "Smooth and rich butter.",
      type:'Butter',
    },
    {
      id: 19,
      name: "Yogurt",
      image: require('../assets/imgs/yogurt.png'),
      price: 1.00,
      description: "Natural and creamy yogurt.",
      type:'Yogurt',
    },
    {
      id: 20,
      name: "Diet Coke",
      image: require('../assets/imgs/ditecoca.png'),
      price: 1.99,
      description: "355ml, Price",
      type:'Beverages',
    },
    {
      id: 21,
      name: "Sprite Can",
      image: require('../assets/imgs/sprite.png'),
      price: 1.50,
      description: "325ml, Price",
      type:'Beverages',
    },
    {
      id: 22,
      name: "Apple & Grape Juice",
      image: require('../assets/imgs/tree-top.png'),
      price: 15.99,
      description: "2L, Price",
      type:'Beverages',
    },
    {
      id: 23,
      name: "Orenge Juice",
      image: require('../assets/imgs/tree-top2.png'),
      price: 15.99,
      description: "2L, Price",
      type:'Beverages',
    },
    {
      id: 24,
      name: "ACoca Cola Can",
      image: require('../assets/imgs/cocacola.png'),
      price: 15.99,
      description: "325ml, Price",
      type:'Beverages',
    },
    {
      id: 25,
      name: "Pepsi Can",
      image: require('../assets/imgs/pepsi.png'),
      price: 15.99,
      description: "330ml, Price",
      type:'Beverages',
    },
  ];

  export default products;
